from setuptools import setup, find_packages

"""
Setup script for the 'whowroteit' package.

This script uses setuptools to package the 'whowroteit' project which is designed to classify text based on whether it was written by a human or generated by an AI.

Attributes:
    VERSION (str): Version number of the package.
    DESCRIPTION (str): Brief description of the package.
    LONG_DESCRIPTION (str): Detailed description of the package.

Functions:
    setup(): Configures the package setup

"""


VERSION = '0.0.1'
DESCRIPTION = 'Human Vs AI Text Classifier'
LONG_DESCRIPTION = 'A package that allows user to identify whether a text is human generated or AI generated'

# Setting up
setup(
    name="whowroteit",
    version=VERSION,
    author='Ritika Kumar, Xin Wang, Ardavan Mehdizadeh',
    author_email='kumar.riti@northeastern.edu, wang.xin18@northeastern.edu, mehdizadeh.a@northeastern.edu',
    description=DESCRIPTION,
    # To find all packages in the directory
    packages=find_packages(),
    # List of dependencies
    install_requires=['pandas', 'numpy', 'scikit-learn', 'tensorflow', 'spacy', 'nltk', 'matplotlib', 'transformers', 'sentence-transformers==2.2.2', 'xgboost', 'InstructorEmbedding', 'pickle' ],
    keywords=['python', 'classification', 'AIvsHuman', 'text']
)
